<?php echo $this->renderInc('head');?>
  <meta http-equiv="X-UA-Compatible" content="IE=7" />
<title>报表系统</title>
<?php echo \Sooh\DWZ\phtml::header();?>
<style>
	.tableStd {margin:5;border: 1px solid #d3d3d3; border-radius: 5px; background-color:#fefefe;}
	.tableStd td {border-right: 1px solid #e0e0e0;   border-bottom: 1px solid #e0e0e0; padding:5;}
	.tableStd th {border-right: 1px solid #e0e0e0;   border-bottom: 1px solid #e0e0e0; padding:5;}
	.linkBtn {}
			.divChartDefault {margin:5px; 
			border: 5px solid #dedede;
			-moz-border-radius: 15px;      /* Gecko browsers */
			-webkit-border-radius: 15px;   /* Webkit browsers */
			border-radius:15px;            /* W3C syntax */
			width:720px;height:400px;float:left
		}
		#divReturnBtn
		{
			position:absolute;
			float:left;
			z-index:3;
			text-align:center;
			width:57px;
			height:30px;
			left:0px;
			top: 760px;
			background-color:#00CCFF;
			border: 5px solid #0066FF;
			-moz-border-radius: 15px;      /* Gecko browsers */
			-webkit-border-radius: 15px;   /* Webkit browsers */
			border-radius:15px;
		}
</style>
<script type="text/javascript">
$(function(){
	DWZ.init("<?php echo \Sooh\Base\Ini::getInstance()->get('request.baseUri')."/dwz/dwz.frag.xml";?>", {
		loginUrl:"<?php echo \Sooh\DB\Acl\Acl::getInstance()->urlLogin().'&__ONLY__=body';?>", loginTitle:"登录",	// 弹出登录对话框
//		loginUrl:"login.html",	// 跳到登录页面
		statusCode:{ok:200, error:300, timeout:301}, //【可选】
		keys: {statusCode:"statusCode", message:"message"}, //【可选】
		pageInfo:{pageNum:"pageid", numPerPage:"pagesize", orderField:"orderField", orderDirection:"orderDirection"}, //【可选】
		debug:false,	// 调试模式 【true|false】
		callback:function(){
			initEnv();
			$("#themeList").theme({themeBase:"themes"});
			//setTimeout(function() {$("#sidebar .toggleCollapse div").trigger("click");}, 10);
		}
	});
});
</script>
 </head>
 <body scroll="no">
<div id="layout">
		<div id="header">
			<div class="headerNav">
				<a class="logo" href="http://j-ui.com">标志</a>
				<ul class="nav">
					<li id="switchEnvBox"><a href="javascript:"><div class="selected">蓝(切换)</div></a>
						<ul class="themeList" id="themeList">
							<li theme="default"><div class="selected">蓝色</div></li>
							<li theme="green"><div>绿色</div></li>
							<li theme="purple"><div>紫色</div></li>
							<li theme="silver"><div>银色</div></li>
							<li theme="azure"><div>天蓝</div></li>
						</ul>
					</li>
					<li><a href="changepwd.html" target="dialog" width="600">修改密码</a></li>
					<li><a href="<?php echo \Sooh\Base\Tools::uriTpl(array('__LOGOUT__'=>'1'));?>">退出</a></li>
				</ul>
			</div>
		
			<!-- 更改leftside用的, 缩小了（85-50,90-55）dwz\themes\default\images\header_bg.png, 以及本页面上面定义的css：#header{height:50px} 和 #leftside, #container, #splitBar, #splitBarProxy{top:55px}-->
			<!--
			<div id="navMenu">
				<ul>
					<li class="selected"><a href="sidebar_1.html"><span>资讯管理</span></a></li>
					<li><a href="sidebar_2.html"><span>订单管理</span></a></li>
					<li><a href="sidebar_1.html"><span>产品管理</span></a></li>
					<li><a href="sidebar_2.html"><span>会员管理</span></a></li>
					<li><a href="sidebar_1.html"><span>服务管理</span></a></li>
					<li><a href="sidebar_2.html"><span>系统设置</span></a></li>
				</ul>
			</div>
			-->
		</div>

		<div id="leftside">
			<div id="sidebar_s">
				<div class="collapse">
					<div class="toggleCollapse"><div></div></div>
				</div>
			</div>
			<div id="sidebar">
				<div class="toggleCollapse"><h2>主菜单</h2><div>收缩</div></div>
				<?php echo \Sooh\DWZ\phtml::menuleft($this->menuleft);?>
			</div>
		</div>
		<div id="container">
			<div id="navTab" class="tabsPage">
				<div class="tabsPageHeader">
					<div class="tabsPageHeaderContent"><!-- 显示左右控制时添加 class="tabsPageHeaderMargin" -->
						<ul class="navTab-tab">
							<li tabid="main" class="main"><a href="javascript:;"><span><span class="home_icon">我的主页</span></span></a></li>
						</ul>
					</div>
					<div class="tabsLeft">left</div><!-- 禁用只需要添加一个样式 class="tabsLeft tabsLeftDisabled" -->
					<div class="tabsRight">right</div><!-- 禁用只需要添加一个样式 class="tabsRight tabsRightDisabled" -->
					<div class="tabsMore">more</div>
				</div>
				<ul class="tabsMoreList">
					<li><a href="javascript:;">我的主页</a></li>
				</ul>
				<div class="navTab-panel tabsPageContent layoutBox">
					<div class="page unitBox">
						..........................................................
					</div>
					
				</div>
			</div>
		</div>

	</div>
	 <div id="footer">没有公告。。。</div>
<?php 
//echo $this->renderInc('foot');
echo "</body></html>";
