<?php 
$this->htmlHeadPart('<title>config表数据管理</title>');
$this->htmlHeadPart(\Sooh\DWZ\phtml::header());
$this->htmlHeadPart('<script type="text/javascript">
$(function(){
	DWZ.init("'. \Sooh\Base\Ini::getInstance()->get('request.baseUri').'/dwz/dwz.frag.xml", {
		loginUrl:"'.\Sooh\DB\Acl\Acl::getInstance()->urlLogin().'", 
		statusCode:{ok:200, error:300, timeout:301}, //【可选】
		keys: {statusCode:"statusCode", message:"message"}, //【可选】
		pageInfo:{pageNum:"pageid", numPerPage:"pagesize", orderField:"orderField", orderDirection:"orderDirection"}, //【可选】
		debug:false,	// 调试模式 【true|false】
		callback:function(){
			$("#themeList").theme({themeBase:"themes"});
		}
	});
});
</script>');
echo $this->renderInc('head');
?>
<body>
<br/><br/><br/><br/><center><div defh="150" class="panel" style="display: block;width:400px;">
		<div class="panelHeader"><div class="panelHeaderContent"><h1 style="cursor: move;"> </h1></div></div>
		<div class="panelContent" style="height: 150px;">
	<div class="pageContent" >
			<div class="pageFormContent" layoutH="58"><br/><br/>
					您已退出系统。<a href="<?php echo \Sooh\Base\Tools::uriTpl(array());?>"><u>重新登入</u></a>
			</div>
	</div>
</div><div class="panelFooter"><div class="panelFooterContent"></div></div></div></center>
<?php 
echo $this->renderInc('foot');
