<?php
$pager=$this->pager;
$str  = '<div class="panelBar">';
if(is_array($pager->enumPagesize)){
	$tmp = $pager->enumPagesize;
}else{
	$tmp = explode(',', $pager->enumPagesize);
}
$str .= '<div class="pages"><span>显示</span>';
$str .=  '<select class="combox" name="numPerPage" onchange="navTabPageBreak({numPerPage:this.value})">';
foreach($tmp as $n) {
	$str .=  "<option value=\"$n\" ".($n==$pager->page_size?'selected':'').">$n</option>";
}
$str .=  '</select><span>条，共'. $pager->total. '条</span>';
$str .=  "</div>\n";

$str .=  "<div class=\"pagination\" targetType=\"navTab\" totalCount=\"{$pager->total}\" numPerPage=\"{$pager->page_size}\" pageNumShown=\"10\" currentPage=\"".($pager->pageid())."\"></div>";
$str .=  '</div>';
echo $str;