<div id="leftside">
	<div id="sidebar_s">
		<div class="collapse">
			<div class="toggleCollapse"><div></div></div>
		</div>
	</div>
	<div id="sidebar">
		<div class="toggleCollapse"><h2>主菜单</h2><div>收缩</div></div>
		<div class="accordion" fillSpace="sideBar">
<?php
/**
 * 
 * @param \Sooh\Base\Acl\Menu $menu
 * @param \Sooh\Base\Acl\Menu $child
 */
function showMenuDefaultType($menu,$child=null)
{
	if(!empty($menu->children)){
		echo '<div class="accordionHeader"><h2><span>Folder</span>'.$menu->capt."</h2></div>\n";
		echo '<div class="accordionContent"><ul class="tree treeFolder"><!--treeCheck-->'."\n";
		foreach($menu->children as $child){//external="true" means include html head 
			if($child->options['external']){
				echo '<li><a href="'.$child->url.'" external="true" target="navTab" rel="page_'.$child->capt.'">'.$child->capt."</a></li>\n";
			}else{
				echo '<li><a href="'.$child->url.'" target="navTab" rel="page_'.$child->capt.'">'.$child->capt."</a></li>\n";
			}
		}
		echo "</div>\n";
	}
}
$tmp = $this->leftmenus->children;
foreach($tmp as $menu){
	showMenuDefaultType($menu);
}
?>

				
		</div>
	</div>
</div>