<?php
$formSearch = \Sooh\Base\Form\Broker::getCopy('default');
$formSearch->setRenderer(new \Lib\Misc\DWZ());
?>
<form id="pagerForm" method="post" action="<?php echo \Sooh\Base\Tools::uri(array());?>">
	<?php echo $formSearch->renderHiddenAfter(0); ?>
</form>

<div class="pageHeader">
	<?php echo $formSearch->renderFormTag('onsubmit="return navTabSearch(this);"');?>
	<div class="searchBar">
		<table class="searchContent"><tr><?php echo $formSearch->renderDefault('<td>{capt} {input}</td>'); ?></tr></table>
		<div class="subBar">
			<ul>
				<li><div class="buttonActive"><div class="buttonContent"><button type="submit">检索</button></div></div></li>
				<!--<li><a class="button" href="demo_page6.html" target="dialog" mask="true" title="查询框"><span>高级检索</span></a></li>-->
			</ul>
		</div>
	</div>
	</form>
</div>

<div class="pageContent">
	<div class="panelBar">
		<ul class="toolBar">
			<li><a class="add" href="<?php echo \Sooh\Base\Tools::uriTpl(array(),'form');?>" target="navTab" ref="edtSomething"><span>添加</span></a></li>
			<!--<li><a class="delete" href="<?php echo \Sooh\Base\Tools::uriTpl(array('_pkey_val'=>'{pkey_val}'),'delete');?>" target="ajaxTodo" title="确定要删除吗?"><span>删除</span></a></li>-->
			<li><a class="edit" href="<?php echo \Sooh\Base\Tools::uriTpl(array('_pkey_val'=>'{pkey_val}'),'form');?>" target="navTab" ref="edtSomething"><span>修改</span></a></li>
			<li><a class="edit" href="<?php echo \Sooh\Base\Tools::uriTpl(array('_pkey_val'=>'{pkey_val}'),'pwdreset');?>" target="dialog"><span>重置密码</span></a></li>
			<li class="line">line</li>
			<li><a class="icon" href="<?php echo \Sooh\Base\Tools::uriTpl(array('__EXCEL__'=>'1'));?>" target="dwzExport" targetType="navTab" title="实要导出这些记录吗?"><span>导出EXCEL</span></a></li>
			<li><a class="icon" href="<?php echo \Sooh\Base\Tools::uriTpl(array('_pkey_val'=>'{pkey_val}'),'disable');?>" target="ajaxTodo"  title="确定要禁用吗?"><span>禁用帐号</span></a></li>
			<li><a class="icon" href="<?php echo \Sooh\Base\Tools::uriTpl(array('_pkey_val'=>'{pkey_val}'),'enable');?>" target="ajaxTodo"  title="确定要启用吗?"><span>启用帐号</span></a></li>
		</ul>
	</div>
	<table class="table" width="100%" layoutH="138">
		<thead><tr>
				<?php
				$headers = $this->headers;
				foreach($headers as $k=>$v){
					echo "<th width=\"$v\">$k</th>";
				}
				?>
		</tr></thead>
		<tbody>
			<?php
			//$optionsStatus = $formSearch->item('_flgDisable_eq')->options->getPair();
			$rights = $this->rightsEnum;
			
			$records = $this->records;
			
			if(!empty($records)){
				foreach($records as $r){
					echo "<tr target=\"pkey_val\" rel=\"".$r['_pkey_val_']."\">";
					unset($r['_pkey_val_']);
					echo '<td>'.implode('</td><td>', $r)."</td></tr>\n";
				}
			}
			?>
		</tbody>
	</table>
	<?php echo $this->renderInc('dwz_pager');/*$this->pager*/?>
</div>